---
# file: db.yml
- hosts: dbservers
  vars_prompt:
    - name: "root_db_password"
      prompt: "Please specify a MySQL root password"
      private: yes
  tasks:
    - include: ../common/tasks/common.yml tags=common
    - include: ../common/tasks/db.yml tags=db
  handlers:
    - include: ../common/handlers/main.yml
