---
# file: web.yml
- hosts: webservers
  tasks:
    - include: ../common/tasks/common.yml tags=common
    - include: ../common/tasks/web.yml tags=web
  handlers:
    - include: ../common/handlers/main.yml
