
---
# file: common/tasks/db.yml

- name: package install loop
  yum: pkg=${item} state=installed
  with_items:
    - mysql-server
    - MySQL-python
  tags:
    - db

- name: ensure mysql started
  service: name=mysqld state=started
  tags:
    - db

- name: ensure mysql enabled
  service: name=mysqld enabled=yes
  tags:
    - db
  notify: restart mysql  

- name: update mysql root password for all root accounts
  mysql_user: name=root host=$item password=${root_db_password} login_user=root
  with_items:
    - localhost
  tags:
    - db
  ignore_errors: yes
  
- name: update mysql root password for all root accounts
  mysql_user: name=root host=$item password=${root_db_password} login_user=root login_password=${root_db_password}
  with_items:
    - $ansible_hostname
    - 127.0.0.1
    - ::1
  tags:
    - db
  ignore_errors: yes

- name: ensure anonymous users are not in the database
  mysql_user: name='' host=$item state=absent login_user=root login_password=${root_db_password}
  with_items:
    - localhost
    - $inventory_hostname
  tags:
    - db
  ignore_errors: yes

- name: remove the test database
  mysql_db: name=test state=absent login_user=root login_password=${root_db_password}
  tags:
    - db

- name: create mysql db
  mysql_db: name=appdb login_user=root login_password=${root_db_password} 
  tags:
    - db

- name: create mysql user
  mysql_user: name=user login_user=root login_password=${root_db_password} password=insecure priv=appdb.*:ALL
  tags:
    - db
