---
# file: common/handlers/main.yml

- name: ping all
  command: ping -c 3 $item
  with_items:
    - web-1.example.com
    - web-2.example.com
    - app-1.example.com
    - app-2.example.com
    - db-1.example.com
    - db-2.example.com
    - ansible.example.com

- name: restart network
  service: name=network state=restarted
  notify:
    - ping all

- name: restart mysql
  service: name=mysqld state=restarted

- name: restart apache
  service: name=httpd state=restarted
